version: '3.8'
services:
  cs:
    image: nginx:alpine
    ports:
      - ${PORT}:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the custom config
