version: '3.8'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./src:/usr/share/nginx/html:ro
    environment:
      - NGINX_PORT=${PORT:-80} # Default to 80 if PORT env variable is not set
    ports:
      - "${PORT:-80}:80"  # Maps the port to host
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
