services:
  apache:
    image: httpd:latest
    container_name: apache_server
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs/
    environment:
      - PORT=${PORT:-80}
