services:
  web:
    container_name: HayaseDB-cs
    image: nginx:latest
    ports:
      - ${PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html/
    restart: always